# Generated by Django 4.2.4 on 2023-08-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campos", "0002_campo_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="app",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
