version: '3.8'

env:
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${{ secrets.DATABASE_USER }}
      POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
      POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASS }}

volumes:
  postgres-data:
