 on:
   workflow_run:
     workflows: ["Django CI"]
     types: [completed]

 jobs:
   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - run: echo "First workflow was a failure"
       - run: echo ${{ github.event.workflow_run }}
